// 500 palabras de inglés organizadas en 10 semanas (50 por semana)
// Niveles A2 -> B2, las más útiles para business + day-to-day
const PALABRAS = {
  1: [
    {en: "achieve", es: "lograr", ej: "We achieved our sales goal.", emoji: "🎯"},
    {en: "afford", es: "permitirse", ej: "I can't afford a new car.", emoji: "💰"},
    {en: "allow", es: "permitir", ej: "We allow remote work.", emoji: "✅"},
    {en: "amount", es: "cantidad", ej: "A large amount of money.", emoji: "🔢"},
    {en: "approach", es: "enfoque / acercarse", ej: "We need a new approach.", emoji: "➡️"},
    {en: "available", es: "disponible", ej: "Are you available tomorrow?", emoji: "🟢"},
    {en: "avoid", es: "evitar", ej: "Avoid that mistake.", emoji: "🚫"},
    {en: "behavior", es: "comportamiento", ej: "His behavior was strange.", emoji: "🎭"},
    {en: "benefit", es: "beneficio", ej: "The benefits are clear.", emoji: "🎁"},
    {en: "borrow", es: "pedir prestado", ej: "Can I borrow your pen?", emoji: "🤲"},
    {en: "budget", es: "presupuesto", ej: "We're over budget.", emoji: "📊"},
    {en: "challenge", es: "desafío", ej: "It's a big challenge.", emoji: "🏔️"},
    {en: "claim", es: "reclamar / afirmar", ej: "She claims it's true.", emoji: "📢"},
    {en: "concern", es: "preocupación", ej: "I share your concern.", emoji: "😟"},
    {en: "confirm", es: "confirmar", ej: "Please confirm the meeting.", emoji: "✔️"},
    {en: "consider", es: "considerar", ej: "Consider all options.", emoji: "🤔"},
    {en: "contain", es: "contener", ej: "The box contains books.", emoji: "📦"},
    {en: "decrease", es: "disminuir", ej: "Sales decreased last month.", emoji: "📉"},
    {en: "deliver", es: "entregar", ej: "We deliver on time.", emoji: "📬"},
    {en: "deserve", es: "merecer", ej: "You deserve a break.", emoji: "🏅"},
    {en: "discover", es: "descubrir", ej: "We discovered a bug.", emoji: "🔍"},
    {en: "due", es: "debido / vencido", ej: "The payment is due Friday.", emoji: "📅"},
    {en: "enough", es: "suficiente", ej: "That's enough for today.", emoji: "🛑"},
    {en: "expect", es: "esperar (esperarse)", ej: "I expect good results.", emoji: "🔮"},
    {en: "fail", es: "fallar", ej: "Don't fail the test.", emoji: "❌"},
    {en: "fee", es: "tarifa", ej: "There's a service fee.", emoji: "💵"},
    {en: "figure out", es: "averiguar", ej: "Let me figure it out.", emoji: "💡"},
    {en: "goal", es: "objetivo", ej: "Our goal is growth.", emoji: "🥅"},
    {en: "growth", es: "crecimiento", ej: "Steady growth this year.", emoji: "📈"},
    {en: "hire", es: "contratar", ej: "We hired three people.", emoji: "🤝"},
    {en: "improve", es: "mejorar", ej: "We must improve quality.", emoji: "⬆️"},
    {en: "income", es: "ingresos", ej: "Annual income increased.", emoji: "💸"},
    {en: "increase", es: "aumentar", ej: "Prices will increase.", emoji: "📈"},
    {en: "issue", es: "problema / asunto", ej: "We have an issue.", emoji: "⚠️"},
    {en: "lack", es: "falta", ej: "Lack of resources.", emoji: "🕳️"},
    {en: "manage", es: "gestionar", ej: "She manages the team.", emoji: "👔"},
    {en: "owe", es: "deber (dinero)", ej: "I owe you 50 euros.", emoji: "🧾"},
    {en: "own", es: "poseer / propio", ej: "I own this car.", emoji: "🔑"},
    {en: "perform", es: "realizar / actuar", ej: "We performed well.", emoji: "🎤"},
    {en: "provide", es: "proporcionar", ej: "We provide support.", emoji: "🎁"},
    {en: "raise", es: "subir / aumentar", ej: "Raise your hand.", emoji: "✋"},
    {en: "rather", es: "más bien / preferir", ej: "I'd rather stay home.", emoji: "🔄"},
    {en: "reach", es: "alcanzar", ej: "We reached the target.", emoji: "🎯"},
    {en: "reduce", es: "reducir", ej: "Reduce costs by 10%.", emoji: "🔻"},
    {en: "require", es: "requerir", ej: "This requires effort.", emoji: "📋"},
    {en: "save", es: "ahorrar / guardar", ej: "Save your work.", emoji: "💾"},
    {en: "spend", es: "gastar", ej: "Don't spend too much.", emoji: "💳"},
    {en: "support", es: "apoyar", ej: "I support this idea.", emoji: "🤝"},
    {en: "task", es: "tarea", ej: "Complete this task today.", emoji: "📌"},
    {en: "waste", es: "desperdiciar", ej: "Don't waste time.", emoji: "🗑️"}
  ],
  2: [
    {en: "ability", es: "habilidad", ej: "She has the ability to lead.", emoji: "💪"},
    {en: "accept", es: "aceptar", ej: "I accept your offer.", emoji: "👍"},
    {en: "access", es: "acceso", ej: "Do you have access?", emoji: "🔓"},
    {en: "according to", es: "según", ej: "According to the report.", emoji: "📖"},
    {en: "accurate", es: "preciso", ej: "Accurate data is key.", emoji: "🎯"},
    {en: "actually", es: "en realidad", ej: "Actually, it's true.", emoji: "💬"},
    {en: "add", es: "añadir", ej: "Add salt to the dish.", emoji: "➕"},
    {en: "advice", es: "consejo", ej: "Good advice, thanks.", emoji: "💭"},
    {en: "agree", es: "estar de acuerdo", ej: "I agree with you.", emoji: "🤝"},
    {en: "ahead", es: "adelante / por delante", ej: "Go ahead.", emoji: "⏩"},
    {en: "aim", es: "objetivo / apuntar", ej: "Our aim is clear.", emoji: "🏹"},
    {en: "answer", es: "respuesta", ej: "What's your answer?", emoji: "💬"},
    {en: "anyway", es: "de todos modos", ej: "Thanks anyway.", emoji: "🤷"},
    {en: "appear", es: "aparecer / parecer", ej: "She appears tired.", emoji: "👀"},
    {en: "apply", es: "aplicar / postularse", ej: "Apply for the job.", emoji: "📨"},
    {en: "argue", es: "discutir", ej: "Don't argue with him.", emoji: "🗣️"},
    {en: "arrive", es: "llegar", ej: "We arrived late.", emoji: "🛬"},
    {en: "ask", es: "preguntar / pedir", ej: "Ask a question.", emoji: "❓"},
    {en: "asleep", es: "dormido", ej: "He fell asleep.", emoji: "😴"},
    {en: "attempt", es: "intentar", ej: "A second attempt.", emoji: "🔁"},
    {en: "attend", es: "asistir", ej: "Attend the meeting.", emoji: "🪑"},
    {en: "audience", es: "público", ej: "Large audience tonight.", emoji: "👥"},
    {en: "average", es: "promedio", ej: "Above average performance.", emoji: "➗"},
    {en: "awake", es: "despierto", ej: "Are you awake yet?", emoji: "👁️"},
    {en: "award", es: "premio", ej: "She won an award.", emoji: "🏆"},
    {en: "aware", es: "consciente", ej: "Be aware of the risks.", emoji: "🧠"},
    {en: "balance", es: "equilibrio / saldo", ej: "Work-life balance.", emoji: "⚖️"},
    {en: "base", es: "base", ej: "Our base is here.", emoji: "🏛️"},
    {en: "become", es: "convertirse", ej: "He became CEO.", emoji: "🦋"},
    {en: "begin", es: "comenzar", ej: "Let's begin.", emoji: "🟢"},
    {en: "behave", es: "comportarse", ej: "Behave well.", emoji: "🎓"},
    {en: "believe", es: "creer", ej: "I believe you.", emoji: "🙏"},
    {en: "belong", es: "pertenecer", ej: "This belongs to me.", emoji: "🔗"},
    {en: "beyond", es: "más allá", ej: "Beyond our budget.", emoji: "🌌"},
    {en: "bill", es: "factura", ej: "Pay the bill.", emoji: "🧾"},
    {en: "blame", es: "culpar", ej: "Don't blame me.", emoji: "👉"},
    {en: "boring", es: "aburrido", ej: "The film was boring.", emoji: "🥱"},
    {en: "boss", es: "jefe", ej: "My boss is fair.", emoji: "👔"},
    {en: "bother", es: "molestar", ej: "Don't bother her.", emoji: "😤"},
    {en: "brand", es: "marca", ej: "A famous brand.", emoji: "🏷️"},
    {en: "break", es: "romper / descanso", ej: "Take a break.", emoji: "💔"},
    {en: "bring", es: "traer", ej: "Bring it here.", emoji: "📥"},
    {en: "build", es: "construir", ej: "Build a team.", emoji: "🏗️"},
    {en: "busy", es: "ocupado", ej: "I'm too busy.", emoji: "🏃"},
    {en: "buy", es: "comprar", ej: "I'll buy it.", emoji: "🛒"},
    {en: "cancel", es: "cancelar", ej: "Cancel the order.", emoji: "❌"},
    {en: "capacity", es: "capacidad", ej: "Full capacity reached.", emoji: "📦"},
    {en: "care", es: "cuidar / importar", ej: "I care about you.", emoji: "❤️"},
    {en: "career", es: "carrera profesional", ej: "A long career.", emoji: "💼"},
    {en: "carry", es: "llevar", ej: "Carry this bag.", emoji: "👜"}
  ],
  3: [
    {en: "cause", es: "causa / causar", ej: "What caused the issue?", emoji: "⚡"},
    {en: "celebrate", es: "celebrar", ej: "Let's celebrate!", emoji: "🎉"},
    {en: "certain", es: "cierto / seguro", ej: "I'm certain about it.", emoji: "💯"},
    {en: "change", es: "cambiar", ej: "Change is good.", emoji: "🔄"},
    {en: "charge", es: "cobrar / cargar", ej: "How much do you charge?", emoji: "💳"},
    {en: "cheap", es: "barato", ej: "This is cheap.", emoji: "🪙"},
    {en: "check", es: "verificar", ej: "Check the email.", emoji: "✔️"},
    {en: "choice", es: "elección", ej: "Make a choice.", emoji: "🔀"},
    {en: "choose", es: "elegir", ej: "Choose wisely.", emoji: "👉"},
    {en: "client", es: "cliente", ej: "A new client.", emoji: "🤵"},
    {en: "close", es: "cerrar / cerca", ej: "Close the door.", emoji: "🚪"},
    {en: "collect", es: "recoger / coleccionar", ej: "Collect the data.", emoji: "🗂️"},
    {en: "common", es: "común", ej: "A common mistake.", emoji: "🌐"},
    {en: "compare", es: "comparar", ej: "Compare prices.", emoji: "⚖️"},
    {en: "complain", es: "quejarse", ej: "Don't complain.", emoji: "😠"},
    {en: "complete", es: "completar", ej: "Complete the form.", emoji: "✅"},
    {en: "complex", es: "complejo", ej: "A complex issue.", emoji: "🧩"},
    {en: "conduct", es: "llevar a cabo", ej: "Conduct a study.", emoji: "🎼"},
    {en: "connect", es: "conectar", ej: "Connect the cable.", emoji: "🔌"},
    {en: "contact", es: "contactar", ej: "Contact support.", emoji: "📞"},
    {en: "continue", es: "continuar", ej: "Continue working.", emoji: "▶️"},
    {en: "contract", es: "contrato", ej: "Sign the contract.", emoji: "📄"},
    {en: "control", es: "controlar", ej: "Take control.", emoji: "🎛️"},
    {en: "convince", es: "convencer", ej: "Convince the boss.", emoji: "🗨️"},
    {en: "cost", es: "costar / coste", ej: "It costs 50 euros.", emoji: "💵"},
    {en: "count", es: "contar", ej: "Count the votes.", emoji: "🔢"},
    {en: "cover", es: "cubrir", ej: "Cover the basics.", emoji: "🛌"},
    {en: "create", es: "crear", ej: "Create a plan.", emoji: "✨"},
    {en: "current", es: "actual", ej: "The current state.", emoji: "📍"},
    {en: "customer", es: "cliente", ej: "Happy customer.", emoji: "🛍️"},
    {en: "damage", es: "daño / dañar", ej: "The storm caused damage.", emoji: "💥"},
    {en: "deal", es: "trato / acuerdo", ej: "It's a deal.", emoji: "🤝"},
    {en: "decide", es: "decidir", ej: "Decide now.", emoji: "🎯"},
    {en: "decision", es: "decisión", ej: "Tough decision.", emoji: "⚖️"},
    {en: "deep", es: "profundo", ej: "A deep lake.", emoji: "🌊"},
    {en: "delay", es: "retraso", ej: "There's a delay.", emoji: "⏰"},
    {en: "demand", es: "demandar / demanda", ej: "High demand.", emoji: "📢"},
    {en: "depend", es: "depender", ej: "It depends.", emoji: "🔗"},
    {en: "describe", es: "describir", ej: "Describe yourself.", emoji: "📝"},
    {en: "design", es: "diseñar", ej: "Nice design.", emoji: "🎨"},
    {en: "develop", es: "desarrollar", ej: "Develop a product.", emoji: "🔨"},
    {en: "die", es: "morir", ej: "He died last year.", emoji: "💀"},
    {en: "difference", es: "diferencia", ej: "Big difference.", emoji: "↔️"},
    {en: "discuss", es: "discutir / hablar", ej: "Let's discuss it.", emoji: "💬"},
    {en: "do", es: "hacer", ej: "Do your best.", emoji: "⚙️"},
    {en: "doubt", es: "duda", ej: "Without a doubt.", emoji: "❓"},
    {en: "draw", es: "dibujar", ej: "Draw a picture.", emoji: "✏️"},
    {en: "drop", es: "soltar / caer", ej: "Don't drop it.", emoji: "💧"},
    {en: "early", es: "temprano", ej: "I woke up early.", emoji: "🌅"},
    {en: "earn", es: "ganar (dinero)", ej: "I earn a salary.", emoji: "💰"}
  ],
  4: [
    {en: "edge", es: "borde", ej: "Cutting edge tech.", emoji: "📐"},
    {en: "effect", es: "efecto", ej: "Side effect.", emoji: "✨"},
    {en: "effort", es: "esfuerzo", ej: "Make an effort.", emoji: "💪"},
    {en: "either", es: "cualquiera / tampoco", ej: "Either option works.", emoji: "🔀"},
    {en: "else", es: "otro / más", ej: "Anything else?", emoji: "➕"},
    {en: "employ", es: "emplear", ej: "We employ 50 people.", emoji: "👷"},
    {en: "empty", es: "vacío", ej: "The box is empty.", emoji: "🪫"},
    {en: "encourage", es: "animar", ej: "I encourage you.", emoji: "📣"},
    {en: "engage", es: "comprometerse", ej: "Engage the audience.", emoji: "🤝"},
    {en: "enjoy", es: "disfrutar", ej: "Enjoy your meal.", emoji: "😊"},
    {en: "ensure", es: "asegurar", ej: "Ensure quality.", emoji: "🛡️"},
    {en: "enter", es: "entrar", ej: "Enter the room.", emoji: "🚪"},
    {en: "entire", es: "entero", ej: "The entire team.", emoji: "💯"},
    {en: "equal", es: "igual", ej: "Equal rights.", emoji: "🟰"},
    {en: "escape", es: "escapar", ej: "Escape the city.", emoji: "🏃"},
    {en: "even", es: "incluso / par", ej: "Even better.", emoji: "⚖️"},
    {en: "event", es: "evento", ej: "A big event.", emoji: "🎫"},
    {en: "evidence", es: "prueba", ej: "Strong evidence.", emoji: "🔬"},
    {en: "exchange", es: "intercambio", ej: "Exchange rate.", emoji: "💱"},
    {en: "exist", es: "existir", ej: "Does it exist?", emoji: "✨"},
    {en: "experience", es: "experiencia", ej: "Years of experience.", emoji: "🎓"},
    {en: "explain", es: "explicar", ej: "Explain it again.", emoji: "👨‍🏫"},
    {en: "express", es: "expresar", ej: "Express your view.", emoji: "💬"},
    {en: "extra", es: "extra", ej: "Need extra help.", emoji: "➕"},
    {en: "face", es: "cara / enfrentar", ej: "Face the truth.", emoji: "😀"},
    {en: "factor", es: "factor", ej: "Key factor.", emoji: "🔑"},
    {en: "fair", es: "justo", ej: "Fair deal.", emoji: "⚖️"},
    {en: "fall", es: "caer / caída", ej: "Don't fall.", emoji: "🍂"},
    {en: "fast", es: "rápido", ej: "Move fast.", emoji: "⚡"},
    {en: "fear", es: "miedo", ej: "No fear.", emoji: "😨"},
    {en: "feel", es: "sentir", ej: "I feel good.", emoji: "💗"},
    {en: "few", es: "pocos", ej: "A few minutes.", emoji: "🤏"},
    {en: "field", es: "campo", ej: "Field of work.", emoji: "🌾"},
    {en: "fill", es: "llenar", ej: "Fill the form.", emoji: "🪣"},
    {en: "finally", es: "finalmente", ej: "Finally home.", emoji: "🏁"},
    {en: "find", es: "encontrar", ej: "Find a solution.", emoji: "🔍"},
    {en: "fine", es: "bien / multa", ej: "I'm fine.", emoji: "👌"},
    {en: "finish", es: "terminar", ej: "Finish the report.", emoji: "🏁"},
    {en: "fire", es: "fuego / despedir", ej: "Fire the employee.", emoji: "🔥"},
    {en: "fit", es: "encajar / en forma", ej: "It fits well.", emoji: "🏋️"},
    {en: "fix", es: "arreglar", ej: "Fix the bug.", emoji: "🔧"},
    {en: "flat", es: "piso / plano", ej: "I rent a flat.", emoji: "🏢"},
    {en: "float", es: "flotar", ej: "It floats.", emoji: "🎈"},
    {en: "fly", es: "volar", ej: "Birds fly.", emoji: "✈️"},
    {en: "focus", es: "enfocar", ej: "Focus on goals.", emoji: "🎯"},
    {en: "follow", es: "seguir", ej: "Follow me.", emoji: "👣"},
    {en: "force", es: "forzar / fuerza", ej: "Use force.", emoji: "💪"},
    {en: "forget", es: "olvidar", ej: "Don't forget.", emoji: "🙈"},
    {en: "form", es: "forma / formar", ej: "Fill the form.", emoji: "📝"},
    {en: "forward", es: "adelante / reenviar", ej: "Move forward.", emoji: "⏩"}
  ],
  5: [
    {en: "free", es: "libre / gratis", ej: "Free coffee.", emoji: "🆓"},
    {en: "fresh", es: "fresco", ej: "Fresh bread.", emoji: "🥬"},
    {en: "friend", es: "amigo", ej: "Best friend.", emoji: "👫"},
    {en: "front", es: "frente", ej: "In front of.", emoji: "⬆️"},
    {en: "full", es: "lleno", ej: "Full tank.", emoji: "🥛"},
    {en: "fun", es: "diversión", ej: "Have fun.", emoji: "🎉"},
    {en: "function", es: "función", ej: "It functions well.", emoji: "⚙️"},
    {en: "fund", es: "fondo / financiar", ej: "Hedge fund.", emoji: "💰"},
    {en: "further", es: "más lejos / adicional", ej: "Further info.", emoji: "↗️"},
    {en: "future", es: "futuro", ej: "Bright future.", emoji: "🔮"},
    {en: "gain", es: "ganar / ganancia", ej: "Gain experience.", emoji: "📈"},
    {en: "game", es: "juego", ej: "Play a game.", emoji: "🎮"},
    {en: "gather", es: "reunir", ej: "Gather the team.", emoji: "👥"},
    {en: "general", es: "general", ej: "General manager.", emoji: "🌐"},
    {en: "generate", es: "generar", ej: "Generate leads.", emoji: "⚡"},
    {en: "gentle", es: "suave / amable", ej: "Be gentle.", emoji: "🌸"},
    {en: "get", es: "obtener / conseguir", ej: "Get the keys.", emoji: "🤲"},
    {en: "give", es: "dar", ej: "Give it to me.", emoji: "🎁"},
    {en: "global", es: "global", ej: "Global market.", emoji: "🌍"},
    {en: "go", es: "ir", ej: "Let's go.", emoji: "🚶"},
    {en: "good", es: "bueno", ej: "Good job.", emoji: "👍"},
    {en: "great", es: "genial", ej: "Great idea.", emoji: "🌟"},
    {en: "ground", es: "suelo / terreno", ej: "Solid ground.", emoji: "🌍"},
    {en: "group", es: "grupo", ej: "Work group.", emoji: "👥"},
    {en: "grow", es: "crecer", ej: "Grow the business.", emoji: "🌱"},
    {en: "guess", es: "adivinar", ej: "Guess what.", emoji: "🤔"},
    {en: "guest", es: "invitado", ej: "VIP guest.", emoji: "🛎️"},
    {en: "guide", es: "guiar / guía", ej: "Tour guide.", emoji: "🧭"},
    {en: "habit", es: "hábito", ej: "Good habit.", emoji: "🔁"},
    {en: "half", es: "mitad", ej: "Half done.", emoji: "🌗"},
    {en: "hand", es: "mano", ej: "Give me a hand.", emoji: "✋"},
    {en: "handle", es: "manejar", ej: "Handle it.", emoji: "🎚️"},
    {en: "happen", es: "suceder", ej: "It happens.", emoji: "💥"},
    {en: "happy", es: "feliz", ej: "Happy birthday.", emoji: "😊"},
    {en: "hard", es: "duro / difícil", ej: "Work hard.", emoji: "🪨"},
    {en: "harm", es: "daño", ej: "No harm done.", emoji: "💢"},
    {en: "have", es: "tener", ej: "Have fun.", emoji: "🫴"},
    {en: "head", es: "cabeza / dirigir", ej: "Head of sales.", emoji: "🧠"},
    {en: "health", es: "salud", ej: "Good health.", emoji: "💚"},
    {en: "hear", es: "oír", ej: "I hear you.", emoji: "👂"},
    {en: "heart", es: "corazón", ej: "Heart attack.", emoji: "❤️"},
    {en: "heavy", es: "pesado", ej: "Heavy box.", emoji: "🏋️"},
    {en: "help", es: "ayudar", ej: "Help me.", emoji: "🆘"},
    {en: "hide", es: "esconder", ej: "Hide the gift.", emoji: "🙈"},
    {en: "high", es: "alto", ej: "High quality.", emoji: "⬆️"},
    {en: "hold", es: "sostener", ej: "Hold on.", emoji: "🤲"},
    {en: "hope", es: "esperar / esperanza", ej: "I hope so.", emoji: "🙏"},
    {en: "however", es: "sin embargo", ej: "However, wait.", emoji: "🔀"},
    {en: "huge", es: "enorme", ej: "Huge success.", emoji: "🐘"},
    {en: "human", es: "humano", ej: "Human nature.", emoji: "👤"}
  ],
  6: [
    {en: "idea", es: "idea", ej: "Good idea.", emoji: "💡"},
    {en: "identify", es: "identificar", ej: "Identify the problem.", emoji: "🪪"},
    {en: "image", es: "imagen", ej: "Brand image.", emoji: "🖼️"},
    {en: "imagine", es: "imaginar", ej: "Imagine that.", emoji: "💭"},
    {en: "impact", es: "impacto", ej: "Big impact.", emoji: "💥"},
    {en: "important", es: "importante", ej: "Very important.", emoji: "⭐"},
    {en: "include", es: "incluir", ej: "Include everyone.", emoji: "➕"},
    {en: "indeed", es: "ciertamente", ej: "Indeed, you're right.", emoji: "✅"},
    {en: "industry", es: "industria", ej: "Tech industry.", emoji: "🏭"},
    {en: "influence", es: "influencia", ej: "Big influence.", emoji: "💫"},
    {en: "inform", es: "informar", ej: "Inform the team.", emoji: "📢"},
    {en: "initial", es: "inicial", ej: "Initial phase.", emoji: "🥇"},
    {en: "inside", es: "dentro", ej: "Inside the box.", emoji: "📥"},
    {en: "instead", es: "en lugar de", ej: "Instead of coffee.", emoji: "🔄"},
    {en: "intend", es: "tener intención", ej: "I intend to go.", emoji: "🎯"},
    {en: "interest", es: "interés", ej: "No interest.", emoji: "👀"},
    {en: "internal", es: "interno", ej: "Internal meeting.", emoji: "🏠"},
    {en: "introduce", es: "introducir / presentar", ej: "Introduce yourself.", emoji: "👋"},
    {en: "invest", es: "invertir", ej: "Invest wisely.", emoji: "💰"},
    {en: "involve", es: "involucrar", ej: "Involve the team.", emoji: "🔗"},
    {en: "join", es: "unirse", ej: "Join us.", emoji: "🤝"},
    {en: "judge", es: "juzgar", ej: "Don't judge.", emoji: "⚖️"},
    {en: "keep", es: "mantener / guardar", ej: "Keep going.", emoji: "🗃️"},
    {en: "kind", es: "tipo / amable", ej: "Kind regards.", emoji: "😇"},
    {en: "know", es: "saber / conocer", ej: "I know that.", emoji: "🧠"},
    {en: "knowledge", es: "conocimiento", ej: "Useful knowledge.", emoji: "📚"},
    {en: "land", es: "tierra / aterrizar", ej: "Land the plane.", emoji: "🌍"},
    {en: "large", es: "grande", ej: "Large company.", emoji: "🐘"},
    {en: "last", es: "último / durar", ej: "Last chance.", emoji: "🏁"},
    {en: "late", es: "tarde", ej: "Don't be late.", emoji: "⏰"},
    {en: "lay", es: "poner / yacer", ej: "Lay it down.", emoji: "🛏️"},
    {en: "lead", es: "liderar", ej: "Lead the team.", emoji: "👑"},
    {en: "learn", es: "aprender", ej: "Learn fast.", emoji: "📚"},
    {en: "least", es: "menos", ej: "At least try.", emoji: "🤏"},
    {en: "leave", es: "dejar / irse", ej: "Leave now.", emoji: "👋"},
    {en: "less", es: "menos", ej: "Less is more.", emoji: "🔻"},
    {en: "let", es: "dejar / permitir", ej: "Let me see.", emoji: "🤝"},
    {en: "level", es: "nivel", ej: "High level.", emoji: "📊"},
    {en: "lie", es: "mentir / yacer", ej: "Don't lie.", emoji: "🤥"},
    {en: "life", es: "vida", ej: "Life is good.", emoji: "🌱"},
    {en: "light", es: "luz / ligero", ej: "Turn on the light.", emoji: "💡"},
    {en: "like", es: "gustar / como", ej: "I like it.", emoji: "💖"},
    {en: "likely", es: "probable", ej: "Most likely yes.", emoji: "🎲"},
    {en: "limit", es: "límite", ej: "No limit.", emoji: "🚧"},
    {en: "link", es: "enlace", ej: "Click the link.", emoji: "🔗"},
    {en: "list", es: "lista", ej: "Make a list.", emoji: "📋"},
    {en: "listen", es: "escuchar", ej: "Listen carefully.", emoji: "👂"},
    {en: "little", es: "pequeño / poco", ej: "A little time.", emoji: "🤏"},
    {en: "live", es: "vivir / vivo", ej: "Live stream.", emoji: "🏠"},
    {en: "load", es: "cargar", ej: "Load the truck.", emoji: "📦"}
  ],
  7: [
    {en: "local", es: "local", ej: "Local store.", emoji: "🏘️"},
    {en: "long", es: "largo", ej: "Long day.", emoji: "📏"},
    {en: "look", es: "mirar / parecer", ej: "Look here.", emoji: "👀"},
    {en: "lose", es: "perder", ej: "Don't lose hope.", emoji: "💔"},
    {en: "loud", es: "ruidoso", ej: "Too loud.", emoji: "🔊"},
    {en: "love", es: "amor / amar", ej: "I love it.", emoji: "❤️"},
    {en: "low", es: "bajo", ej: "Low price.", emoji: "⬇️"},
    {en: "lucky", es: "afortunado", ej: "Lucky me.", emoji: "🍀"},
    {en: "main", es: "principal", ej: "Main idea.", emoji: "🏆"},
    {en: "maintain", es: "mantener", ej: "Maintain quality.", emoji: "🛠️"},
    {en: "major", es: "principal / mayor", ej: "Major change.", emoji: "⭐"},
    {en: "make", es: "hacer", ej: "Make sense.", emoji: "🔨"},
    {en: "manner", es: "manera", ej: "Polite manner.", emoji: "🎩"},
    {en: "many", es: "muchos", ej: "Many people.", emoji: "👥"},
    {en: "mark", es: "marca / marcar", ej: "Mark the date.", emoji: "🖊️"},
    {en: "market", es: "mercado", ej: "Free market.", emoji: "🏪"},
    {en: "match", es: "coincidir / partido", ej: "Match made.", emoji: "🔥"},
    {en: "matter", es: "importar / asunto", ej: "It matters.", emoji: "❗"},
    {en: "may", es: "poder (permiso)", ej: "May I help?", emoji: "🙆"},
    {en: "mean", es: "significar / malo", ej: "What do you mean?", emoji: "💬"},
    {en: "measure", es: "medir", ej: "Measure twice.", emoji: "📏"},
    {en: "meet", es: "encontrarse", ej: "Nice to meet you.", emoji: "🤝"},
    {en: "meeting", es: "reunión", ej: "Daily meeting.", emoji: "🪑"},
    {en: "member", es: "miembro", ej: "Team member.", emoji: "🪪"},
    {en: "mention", es: "mencionar", ej: "Don't mention it.", emoji: "💬"},
    {en: "message", es: "mensaje", ej: "Short message.", emoji: "✉️"},
    {en: "method", es: "método", ej: "New method.", emoji: "📐"},
    {en: "middle", es: "medio", ej: "Middle of the day.", emoji: "🎯"},
    {en: "might", es: "podría", ej: "I might come.", emoji: "🤷"},
    {en: "mind", es: "mente", ej: "Never mind.", emoji: "🧠"},
    {en: "minute", es: "minuto", ej: "One minute.", emoji: "⏱️"},
    {en: "miss", es: "perder / extrañar", ej: "I miss you.", emoji: "💔"},
    {en: "mistake", es: "error", ej: "Big mistake.", emoji: "❌"},
    {en: "model", es: "modelo", ej: "Business model.", emoji: "🧱"},
    {en: "moment", es: "momento", ej: "Right moment.", emoji: "⏳"},
    {en: "money", es: "dinero", ej: "More money.", emoji: "💰"},
    {en: "month", es: "mes", ej: "Last month.", emoji: "📅"},
    {en: "more", es: "más", ej: "Want more?", emoji: "➕"},
    {en: "most", es: "la mayoría", ej: "Most people.", emoji: "🔝"},
    {en: "move", es: "mover", ej: "Move forward.", emoji: "➡️"},
    {en: "much", es: "mucho", ej: "Too much.", emoji: "📦"},
    {en: "must", es: "deber", ej: "You must go.", emoji: "❗"},
    {en: "name", es: "nombre", ej: "My name is.", emoji: "🪪"},
    {en: "narrow", es: "estrecho", ej: "Narrow street.", emoji: "↔️"},
    {en: "near", es: "cerca", ej: "Near the office.", emoji: "📍"},
    {en: "necessary", es: "necesario", ej: "Not necessary.", emoji: "❗"},
    {en: "need", es: "necesitar", ej: "I need help.", emoji: "🆘"},
    {en: "neither", es: "ninguno", ej: "Neither one.", emoji: "🚫"},
    {en: "never", es: "nunca", ej: "Never give up.", emoji: "⛔"},
    {en: "new", es: "nuevo", ej: "New product.", emoji: "✨"}
  ],
  8: [
    {en: "next", es: "siguiente", ej: "Next week.", emoji: "▶️"},
    {en: "nice", es: "agradable", ej: "Nice to meet.", emoji: "😊"},
    {en: "no longer", es: "ya no", ej: "No longer here.", emoji: "🚫"},
    {en: "nobody", es: "nadie", ej: "Nobody knows.", emoji: "👻"},
    {en: "noise", es: "ruido", ej: "Loud noise.", emoji: "🔊"},
    {en: "none", es: "ninguno", ej: "None of them.", emoji: "0️⃣"},
    {en: "normal", es: "normal", ej: "Normal day.", emoji: "👌"},
    {en: "note", es: "nota", ej: "Take note.", emoji: "📝"},
    {en: "nothing", es: "nada", ej: "Nothing here.", emoji: "🚫"},
    {en: "notice", es: "notar / aviso", ej: "I noticed it.", emoji: "👁️"},
    {en: "now", es: "ahora", ej: "Right now.", emoji: "⏰"},
    {en: "number", es: "número", ej: "Phone number.", emoji: "🔢"},
    {en: "obvious", es: "obvio", ej: "Obvious answer.", emoji: "🔆"},
    {en: "occur", es: "ocurrir", ej: "It occurred to me.", emoji: "💥"},
    {en: "of course", es: "por supuesto", ej: "Of course!", emoji: "✅"},
    {en: "offer", es: "oferta / ofrecer", ej: "Good offer.", emoji: "🎁"},
    {en: "office", es: "oficina", ej: "At the office.", emoji: "🏢"},
    {en: "often", es: "a menudo", ej: "I often work late.", emoji: "🔁"},
    {en: "old", es: "viejo", ej: "Old friend.", emoji: "👴"},
    {en: "once", es: "una vez", ej: "Once upon a time.", emoji: "1️⃣"},
    {en: "only", es: "solo", ej: "Only one left.", emoji: "☝️"},
    {en: "open", es: "abrir / abierto", ej: "Open the door.", emoji: "🔓"},
    {en: "operate", es: "operar", ej: "Operate the machine.", emoji: "🎛️"},
    {en: "opinion", es: "opinión", ej: "My opinion is.", emoji: "💭"},
    {en: "opportunity", es: "oportunidad", ej: "Big opportunity.", emoji: "🌟"},
    {en: "option", es: "opción", ej: "Best option.", emoji: "🔀"},
    {en: "order", es: "pedido / orden", ej: "Place an order.", emoji: "📋"},
    {en: "ordinary", es: "ordinario", ej: "Ordinary day.", emoji: "😐"},
    {en: "organize", es: "organizar", ej: "Organize the files.", emoji: "🗂️"},
    {en: "other", es: "otro", ej: "The other one.", emoji: "🔄"},
    {en: "outside", es: "fuera", ej: "Outside the box.", emoji: "🌳"},
    {en: "over", es: "sobre / terminado", ej: "It's over.", emoji: "🏁"},
    {en: "owner", es: "dueño", ej: "The owner.", emoji: "🏡"},
    {en: "page", es: "página", ej: "Next page.", emoji: "📄"},
    {en: "pain", es: "dolor", ej: "Back pain.", emoji: "🤕"},
    {en: "paper", es: "papel", ej: "Sheet of paper.", emoji: "📃"},
    {en: "part", es: "parte", ej: "A big part.", emoji: "🧩"},
    {en: "particular", es: "particular", ej: "In particular.", emoji: "🎯"},
    {en: "partner", es: "socio / pareja", ej: "Business partner.", emoji: "🤝"},
    {en: "party", es: "fiesta / partido", ej: "Birthday party.", emoji: "🎉"},
    {en: "pass", es: "pasar", ej: "Pass the salt.", emoji: "🤲"},
    {en: "past", es: "pasado", ej: "In the past.", emoji: "⏮️"},
    {en: "path", es: "camino", ej: "Career path.", emoji: "🛤️"},
    {en: "patient", es: "paciente", ej: "Be patient.", emoji: "😌"},
    {en: "pay", es: "pagar", ej: "Pay the bill.", emoji: "💳"},
    {en: "peace", es: "paz", ej: "World peace.", emoji: "🕊️"},
    {en: "people", es: "gente", ej: "Many people.", emoji: "👥"},
    {en: "percent", es: "por ciento", ej: "Ten percent.", emoji: "💯"},
    {en: "perhaps", es: "quizás", ej: "Perhaps later.", emoji: "🤔"},
    {en: "period", es: "período", ej: "Trial period.", emoji: "⏳"}
  ],
  9: [
    {en: "person", es: "persona", ej: "Nice person.", emoji: "👤"},
    {en: "phone", es: "teléfono", ej: "Call the phone.", emoji: "📱"},
    {en: "pick", es: "elegir / recoger", ej: "Pick one.", emoji: "☝️"},
    {en: "picture", es: "imagen", ej: "Take a picture.", emoji: "🖼️"},
    {en: "piece", es: "pieza", ej: "A piece of cake.", emoji: "🧩"},
    {en: "place", es: "lugar", ej: "Nice place.", emoji: "📍"},
    {en: "plan", es: "plan", ej: "Make a plan.", emoji: "📅"},
    {en: "play", es: "jugar / tocar", ej: "Play music.", emoji: "🎮"},
    {en: "please", es: "por favor / agradar", ej: "Please help.", emoji: "🙏"},
    {en: "point", es: "punto", ej: "Good point.", emoji: "📍"},
    {en: "policy", es: "política", ej: "Company policy.", emoji: "📜"},
    {en: "poor", es: "pobre", ej: "Poor quality.", emoji: "🪙"},
    {en: "popular", es: "popular", ej: "Popular brand.", emoji: "🌟"},
    {en: "position", es: "posición", ej: "Strong position.", emoji: "📍"},
    {en: "possible", es: "posible", ej: "If possible.", emoji: "✅"},
    {en: "post", es: "publicar / correo", ej: "Post a comment.", emoji: "📮"},
    {en: "power", es: "poder", ej: "Power up.", emoji: "⚡"},
    {en: "practice", es: "práctica", ej: "Practice makes perfect.", emoji: "🏋️"},
    {en: "prefer", es: "preferir", ej: "I prefer tea.", emoji: "👍"},
    {en: "prepare", es: "preparar", ej: "Prepare a report.", emoji: "📋"},
    {en: "present", es: "presente / presentar", ej: "Present the data.", emoji: "🎁"},
    {en: "press", es: "presionar / prensa", ej: "Press the button.", emoji: "👆"},
    {en: "pretty", es: "bonito / bastante", ej: "Pretty good.", emoji: "🌸"},
    {en: "prevent", es: "prevenir", ej: "Prevent issues.", emoji: "🛡️"},
    {en: "previous", es: "previo", ej: "Previous job.", emoji: "⏮️"},
    {en: "price", es: "precio", ej: "High price.", emoji: "💲"},
    {en: "private", es: "privado", ej: "Private meeting.", emoji: "🔒"},
    {en: "probably", es: "probablemente", ej: "Probably yes.", emoji: "🎲"},
    {en: "problem", es: "problema", ej: "Big problem.", emoji: "⚠️"},
    {en: "process", es: "proceso", ej: "Slow process.", emoji: "⚙️"},
    {en: "produce", es: "producir", ej: "Produce more.", emoji: "🏭"},
    {en: "product", es: "producto", ej: "New product.", emoji: "📦"},
    {en: "professional", es: "profesional", ej: "Professional team.", emoji: "💼"},
    {en: "profit", es: "beneficio (económico)", ej: "Net profit.", emoji: "💰"},
    {en: "program", es: "programa", ej: "TV program.", emoji: "💻"},
    {en: "project", es: "proyecto", ej: "New project.", emoji: "📋"},
    {en: "promise", es: "promesa / prometer", ej: "I promise.", emoji: "🤞"},
    {en: "promote", es: "promover", ej: "Promote the product.", emoji: "📣"},
    {en: "proper", es: "apropiado", ej: "Proper way.", emoji: "👌"},
    {en: "property", es: "propiedad", ej: "Private property.", emoji: "🏠"},
    {en: "propose", es: "proponer", ej: "Propose a plan.", emoji: "💍"},
    {en: "protect", es: "proteger", ej: "Protect the data.", emoji: "🛡️"},
    {en: "prove", es: "probar / demostrar", ej: "Prove it.", emoji: "✅"},
    {en: "provider", es: "proveedor", ej: "Service provider.", emoji: "🏢"},
    {en: "public", es: "público", ej: "Public space.", emoji: "🌐"},
    {en: "publish", es: "publicar", ej: "Publish a book.", emoji: "📰"},
    {en: "pull", es: "tirar de", ej: "Pull the rope.", emoji: "🪢"},
    {en: "purchase", es: "compra", ej: "Online purchase.", emoji: "🛒"},
    {en: "purpose", es: "propósito", ej: "On purpose.", emoji: "🎯"},
    {en: "push", es: "empujar", ej: "Push the door.", emoji: "👉"}
  ],
  10: [
    {en: "put", es: "poner", ej: "Put it down.", emoji: "📥"},
    {en: "quality", es: "calidad", ej: "High quality.", emoji: "⭐"},
    {en: "question", es: "pregunta", ej: "Ask a question.", emoji: "❓"},
    {en: "quick", es: "rápido", ej: "Quick reply.", emoji: "⚡"},
    {en: "quiet", es: "silencioso", ej: "Quiet please.", emoji: "🤫"},
    {en: "quite", es: "bastante", ej: "Quite good.", emoji: "👌"},
    {en: "range", es: "rango", ej: "Wide range.", emoji: "📊"},
    {en: "rate", es: "tasa / valorar", ej: "Interest rate.", emoji: "📊"},
    {en: "reach", es: "alcanzar", ej: "Reach me by email.", emoji: "🤲"},
    {en: "react", es: "reaccionar", ej: "React quickly.", emoji: "⚡"},
    {en: "read", es: "leer", ej: "Read the book.", emoji: "📖"},
    {en: "ready", es: "listo", ej: "Are you ready?", emoji: "✅"},
    {en: "real", es: "real", ej: "Real story.", emoji: "💎"},
    {en: "realize", es: "darse cuenta", ej: "I realized it.", emoji: "💡"},
    {en: "reason", es: "razón", ej: "Good reason.", emoji: "🧠"},
    {en: "receive", es: "recibir", ej: "Receive the package.", emoji: "📥"},
    {en: "recent", es: "reciente", ej: "Recent news.", emoji: "🆕"},
    {en: "recognize", es: "reconocer", ej: "Recognize the voice.", emoji: "👁️"},
    {en: "record", es: "registro / grabar", ej: "Record the call.", emoji: "🎙️"},
    {en: "refer", es: "referirse", ej: "Refer to the manual.", emoji: "👉"},
    {en: "reflect", es: "reflejar", ej: "Reflect on it.", emoji: "🪞"},
    {en: "refuse", es: "rechazar", ej: "I refuse.", emoji: "🙅"},
    {en: "regard", es: "considerar", ej: "Best regards.", emoji: "💌"},
    {en: "region", es: "región", ej: "Local region.", emoji: "🗺️"},
    {en: "regular", es: "regular", ej: "Regular customer.", emoji: "🔁"},
    {en: "relate", es: "relacionar", ej: "Relate to that.", emoji: "🔗"},
    {en: "release", es: "lanzar / liberar", ej: "Release the product.", emoji: "🚀"},
    {en: "remain", es: "permanecer", ej: "Remain calm.", emoji: "🪨"},
    {en: "remember", es: "recordar", ej: "Remember me?", emoji: "🧠"},
    {en: "remove", es: "quitar", ej: "Remove the file.", emoji: "🗑️"},
    {en: "repeat", es: "repetir", ej: "Repeat please.", emoji: "🔁"},
    {en: "replace", es: "reemplazar", ej: "Replace the part.", emoji: "🔄"},
    {en: "reply", es: "responder", ej: "Quick reply.", emoji: "💬"},
    {en: "report", es: "informe", ej: "Annual report.", emoji: "📊"},
    {en: "represent", es: "representar", ej: "Represent the firm.", emoji: "🎭"},
    {en: "request", es: "solicitud", ej: "Send a request.", emoji: "📨"},
    {en: "respect", es: "respetar", ej: "Respect others.", emoji: "🙏"},
    {en: "respond", es: "responder", ej: "Respond fast.", emoji: "💬"},
    {en: "rest", es: "descansar / resto", ej: "Take a rest.", emoji: "💤"},
    {en: "result", es: "resultado", ej: "Final result.", emoji: "🏆"},
    {en: "return", es: "volver / devolver", ej: "Return home.", emoji: "🔙"},
    {en: "reveal", es: "revelar", ej: "Reveal the plan.", emoji: "🎁"},
    {en: "review", es: "revisar", ej: "Review the code.", emoji: "🔍"},
    {en: "rich", es: "rico", ej: "Rich man.", emoji: "💎"},
    {en: "right", es: "correcto / derecho", ej: "You're right.", emoji: "✅"},
    {en: "rise", es: "subir / aumentar", ej: "Prices rise.", emoji: "📈"},
    {en: "risk", es: "riesgo", ej: "Take a risk.", emoji: "⚠️"},
    {en: "road", es: "carretera", ej: "Long road.", emoji: "🛣️"},
    {en: "role", es: "rol", ej: "Key role.", emoji: "🎭"},
    {en: "rough", es: "duro / áspero", ej: "Rough day.", emoji: "🪨"}
  ]
};
